// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATv8o6pf3B7Shn5NLsrZSykQvHiezDeLs',
    appId: '1:556680712056:web:b354572d0e25aec844c28d',
    messagingSenderId: '556680712056',
    projectId: 'turboboard-59499',
    authDomain: 'turboboard-59499.firebaseapp.com',
    storageBucket: 'turboboard-59499.firebasestorage.app',
    measurementId: 'G-8NTQZJZGJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXPLSjgh-4lFaPk2re3CiesGN6NwfvmXw',
    appId: '1:556680712056:android:887c2ff6de42f3ef44c28d',
    messagingSenderId: '556680712056',
    projectId: 'turboboard-59499',
    storageBucket: 'turboboard-59499.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAuN2QyoBDpy1hE1NJLMD0OuBCcBaxM3g',
    appId: '1:556680712056:ios:a75ce5845bb4eb8344c28d',
    messagingSenderId: '556680712056',
    projectId: 'turboboard-59499',
    storageBucket: 'turboboard-59499.firebasestorage.app',
    iosBundleId: 'com.example.turboBoard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAuN2QyoBDpy1hE1NJLMD0OuBCcBaxM3g',
    appId: '1:556680712056:ios:a75ce5845bb4eb8344c28d',
    messagingSenderId: '556680712056',
    projectId: 'turboboard-59499',
    storageBucket: 'turboboard-59499.firebasestorage.app',
    iosBundleId: 'com.example.turboBoard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATv8o6pf3B7Shn5NLsrZSykQvHiezDeLs',
    appId: '1:556680712056:web:3007a2b8cdd5ec4944c28d',
    messagingSenderId: '556680712056',
    projectId: 'turboboard-59499',
    authDomain: 'turboboard-59499.firebaseapp.com',
    storageBucket: 'turboboard-59499.firebasestorage.app',
    measurementId: 'G-NR1S0V2SL8',
  );
}
